name: torch19
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - click=8.0.1
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - importlib-metadata=3.10.0
  - iniconfig=1.1.1
  - intel-openmp=2021.2.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - more-itertools=8.8.0
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.2.5
  - pillow=8.3.1
  - pip=21.1.3
  - pluggy=0.13.1
  - py=1.10.0
  - pyparsing=2.4.7
  - pytest=6.2.4
  - python=3.8.10
  - python-dateutil=2.8.1
  - pytorch=1.9.0
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - antlr4-python3-runtime==4.8
    - async-timeout==3.0.1
    - cachetools==4.2.2
    - chardet==4.0.0
    - charset-normalizer==2.0.1
    - fsspec==2021.7.0
    - future==0.18.2
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - greenlet==1.1.0
    - grpcio==1.38.1
    - hydra-core==1.1.0
    - idna==3.2
    - importlib-resources==5.2.0
    - markdown==3.3.4
    - msgpack==1.0.2
    - multidict==5.1.0
    - oauthlib==3.1.1
    - omegaconf==2.1.0
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.0
    - pynvim==0.4.3
    - pytorch-lightning==1.3.8
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.4.1
    - tqdm==4.61.2
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - yarl==1.6.3
