name: hydra1.1
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cpuonly=1.0
  - intel-openmp=2021.3.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuv=1.40.0
  - mkl=2021.3.0
  - ncurses=6.2
  - ninja=1.10.2
  - openssl=1.1.1k
  - pip=21.1.3
  - python=3.8.10
  - pytorch=1.9.0
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - typing_extensions=3.10.0.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - antlr4-python3-runtime==4.8
    - hydra-core==1.1.0
    - importlib-resources==5.2.0
    - omegaconf==2.1.0
    - pyyaml==5.4.1
    - zipp==3.5.0
